myproject/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('u/', include('users.urls')),
    path('data/', include('charts.urls')),
    path('editor/', include('editor.urls')),
    path('', include('quizzes.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('favicon.ico/', RedirectView.as_view(url=staticfiles_storage.url('quizzes/img/favicon.ico'))),
]

quizzes/urls.py
from django.urls import path

from .views import HomeView, TopicDetailView, QuizView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('topic/<int:pk>/', TopicDetailView.as_view(), name='topic_detail'),
    path('quiz/<int:topic_id>/', QuizView.as_view(), name='quiz'),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views as users_views

urlpatterns = [
    path('register/', users_views.RegisterView.as_view(), name='register'),
    path('register/student/', users_views.StudentRegisterView.as_view(), name='register_student'),
    path('register/teacher/', users_views.TeacherRegisterView.as_view(), name='register_teacher'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password-reset.html',
                                              email_template_name='users/email/password_reset_email.html',
                                              subject_template_name='users/email/password_reset_subject.txt'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password-reset-done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password-reset-confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password-reset-complete.html'),
         name='password_reset_complete'),
    path('profile/', users_views.UserUpdateView.as_view(), name='profile'),
    path('password/', users_views.CustomPasswordChangeView.as_view(), name='password_change'),
]

quizzes/models.py
import datetime

from django.db import models
from django.db.models import F, Count

from users.models import User

QUIZ_INTERVALS = (1, 3, 7, 13, 21, 30)
MAX_SCORE = len(QUIZ_INTERVALS) - 1


class Topic(models.Model):
    """A Django model representing a 'Topic', that is, a thematic grouping of Words.

    Topics can be further illustrated using descriptions, and can be controlled.
    """

    name = models.CharField(max_length=32, unique=True)
    long_desc = models.CharField(max_length=255, blank=True, verbose_name="Long Description")
    short_desc = models.CharField(max_length=10, default='❓🧠❓', verbose_name="Emoji Description",
                                  help_text="Illustrate the Topic with a few emoji. "
                                            "On Mac? Press CTRL+CMD+Space. On Windows? Press Windows key + fullstop.")
    is_hidden = models.BooleanField(default=False, verbose_name="Hide Topic",
                                    help_text="Hide the Topic from view. No quizzes can be taken "
                                              "using this Topic while it is hidden. "
                                              "Topics which contain fewer than four words are hidden regardless.")
    available_from = models.DateField(default=datetime.date.today)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def words_due_revision(self, user, today=datetime.date.today()):
        """Returns a queryset containing this Topic's Words due for revision today (or on specified date)."""
        words_in_topic = Word.objects.filter(topics=self)
        words_not_due = Word.objects.filter(topics=self, wordscore__next_review__gt=today, wordscore__student=user)

        # words due revision = all words in given topic - words NOT due revision by given user
        return words_in_topic.difference(words_not_due)

    @staticmethod
    def all_topics_words_due_revision(user, today=datetime.date.today()):
        """Returns a queryset containing all Words across all Topics due for revision today (or on specified date)."""
        # word must part of a live topic to be counted
        all_words = Word.objects.filter(topics__in=Topic.live_topics().values_list('id'))
        words_not_due = all_words.filter(wordscore__next_review__gt=today, wordscore__student=user)
        return all_words.difference(words_not_due)

    @staticmethod
    def live_topics(today=datetime.date.today()):
        """Returns a queryset containing all live Topics, i.e. those with >= 4 Words, not future dated, not hidden."""
        return Topic.objects.annotate(word_count=Count('words')).filter(word_count__gte=4,
                                                                        available_from__lte=today, is_hidden=False)


class Word(models.Model):
    """A Django model representing a Word, the items that the User is attempting to memorise.

    Each Word is formed of a definition in its 'origin' (known) and 'target' (unknown) language.
    Each Word can belong to multiple (or 0) Topics.
    Each Word is related to students (i.e. Users) via a WordScore object.
    """

    origin = models.CharField(max_length=100, unique=True)
    target = models.CharField(max_length=100, unique=True)
    topics = models.ManyToManyField(Topic, related_name='words', blank=True)
    students = models.ManyToManyField(User, through='WordScore',
                                      through_fields=('word', 'student'), related_name='words')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.origin} -> {self.target}'


class WordScore(models.Model):
    """A Django model representing a particular User's score for a particular Word.

    This model is the basis of the application's spaced repetition scheduling algorithm, tracking key data points
    to estimate a User's current familiarity with a Word.
    """

    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    consecutive_correct = models.PositiveIntegerField(default=0)
    times_seen = models.PositiveIntegerField(default=1)
    times_correct = models.PositiveIntegerField(default=0)
    last_updated = models.DateTimeField(auto_now=True)
    next_review = models.DateField(default=datetime.date.today)

    class Meta:
        unique_together = ('word', 'student')

    def __str__(self):
        return f'{self.student} / {self.word}: {self.score()}'

    def score(self):
        """Enforce a maximum score for each word."""
        return min(self.consecutive_correct, MAX_SCORE)

    def set_next_review(self, today=datetime.date.today()):
        """Updates the next_review field with the appropriate date based on the current Score."""
        days_to_add = QUIZ_INTERVALS[self.score()]
        self.next_review = today + datetime.timedelta(days=days_to_add)


class QuizResults(models.Model):
    """A Django model representing the results of a Quiz.

     An entry is generated at the end of each Quiz, summarising the results and the number of points earned by the User.
     """

    student = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    date_created = models.DateField(default=datetime.date.today)
    correct_answers = models.PositiveIntegerField(default=0)
    incorrect_answers = models.PositiveIntegerField(default=0)
    points = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"Quiz Results: {self.student.get_full_name()} / {self.topic} on {self.date_created}"

    @staticmethod
    def update_user_streak(student, today=datetime.date.today()):
        """Updates user's streak if this is their first quiz taken today."""
        yesterday = today - datetime.timedelta(1)
        quizzes_since_yesterday = QuizResults.objects.filter(
            student=student, date_created__gte=yesterday).values_list('date_created', flat=True)

        if today not in quizzes_since_yesterday:
            if yesterday in quizzes_since_yesterday:
                # student is continuing an existing streak
                student.streak = F('streak') + 1
            else:
                # student is starting a new streak
                student.streak = 1
            student.save(update_fields=['streak'])

    @staticmethod
    def get_user_streak(student):
        """Gets the user's current streak as of now. (User.streak stores the streak as of its latest update)."""
        yesterday = datetime.date.today() - datetime.timedelta(1)
        if QuizResults.objects.filter(student=student, date_created__gte=yesterday).exists():
            streak = student.streak
        else:
            streak = 0
        return streak

quizzes/forms.py
from crispy_bulma.layout import Submit, Reset, FormGroup, Row, Column
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from django import forms

from django.forms import DateInput, ModelForm, Textarea
from django.urls import reverse_lazy
from emoji_picker.widgets import EmojiPickerTextInput

from quizzes.models import Topic, Word


class CustomMultiChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, topic):
        # nicer styling for checkboxes
        return topic.name


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ['name', 'long_desc', 'short_desc', 'available_from', 'is_hidden']
        widgets = {
            'short_desc': EmojiPickerTextInput(attrs={'size': 10, 'style': 'font-size: xx-large'}),
            'long_desc': Textarea(attrs={'rows': 3, 'cols': 20}),
            'available_from': DateInput(attrs={'type': 'date'}),
        }

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Save', css_class='is-success has-text-weight-semibold'))


class WordForm(ModelForm):
    class Meta:
        model = Word
        fields = ['origin', 'target']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_action = reverse_lazy('add_word')
    helper.form_class = 'word-create-form'
    helper.layout = Layout(
        Field('origin'),
        Field('target'),
        FormGroup(
            Reset('reset', 'Cancel', css_class='is-outlined has-text-weight-semibold', css_id='cancel-button'),
            Submit('submit', 'Save', css_class='is-success has-text-weight-semibold'))
    )


class WordUpdateForm(ModelForm):
    class Meta:
        model = Word
        fields = ['origin', 'target', 'topics']

    topics = CustomMultiChoiceField(
        queryset=Topic.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    helper = FormHelper()
    helper.layout = Layout(
        Field('origin'),
        Field('target'),
        Field('topics'),
        FormGroup(
            Submit('submit', 'Update', css_class='is-success has-text-weight-semibold')),
    )


class WordFilterForm(forms.Form):
    helper = FormHelper()
    helper.form_method = 'GET'
    helper.form_action = reverse_lazy('filter_words')
    helper.form_id = 'word-filter-form'
    helper.form_show_labels = False
    helper.layout = Layout(
        Row(
            Column(Field('search')),
            Column(Field('topic'))),
        FormGroup(
            Reset('reset', 'Reset', css_class='is-outlined', css_id='filter-reset'),
            Submit('submit', 'Submit', css_class='is-success has-text-weight-semibold', css_id='filter-submit')))

    # Individual field settings
    search = forms.CharField(required=False,
                             widget=forms.TextInput(attrs={'placeholder': 'Search by Target or Origin'}))
    topic = forms.ChoiceField(required=False,
                              choices=[('', '** All Topics **'), (-1, '** No Topics **')] +
                                      list(Topic.objects.order_by('name').values_list('pk', 'name')))

quizzes/views.py
import datetime
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import FilteredRelation, Q, F, Count, ExpressionWrapper, BooleanField
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView

from quizzes.models import Topic, Word
from quizzes.utils import quiz_builder
from quizzes.utils.quiz_logger import process_results


class HomeView(LoginRequiredMixin, ListView):
    """View responsible for rendering the homepage, including the key details of the available Topics."""
    model = Topic
    template_name = 'quizzes/home.html'
    context_object_name = 'topics'

    def get_queryset(self):
        # topics that are hidden, future-scheduled, or have fewer than 4 words, are only visible to teachers
        today = datetime.date.today()
        topics = Topic.objects.annotate(
            word_count=Count('words', distinct=True),
            future_avail_from=ExpressionWrapper(Q(available_from__gt=today), output_field=BooleanField()),
            is_visible=ExpressionWrapper(Q(is_hidden=False) & Q(future_avail_from=False), output_field=BooleanField()))

        if not self.request.user.is_teacher:
            # exclude non-visible topics from student's homepage, add details of words due revision
            student = self.request.user
            topics = topics.filter(is_visible=True, word_count__gte=4)\
                .annotate(words_due=F('word_count') - Count('id', filter=Q(words__wordscore__next_review__gt=today) &
                                                            Q(words__wordscore__student=student)))

        return topics.order_by('available_from', 'date_created')


class TopicDetailView(LoginRequiredMixin, DetailView):
    """View responsible for rendering the Topic Detail page, including obtaining the user's current scores."""
    model = Topic
    fields = ['name', 'long_desc', 'short_desc']

    def get_context_data(self, **kwargs):
        """Get the user's scores for all Words in the Topic, including Words where no WordScore currently exists."""
        context = super().get_context_data(**kwargs)

        # get the ORM to perform an outer join in order to add Words without WordScores
        qs = Word.objects.filter(topics=context['topic'])\
            .annotate(joinscore=FilteredRelation('wordscore', condition=Q(wordscore__student=self.request.user)),)\
            .order_by('origin')\
            .values_list('origin', 'target', 'joinscore__consecutive_correct', 'joinscore__next_review')

        # adjust words with no WordScores to sensible default values, or when date is in past
        words_with_scores = []
        today = datetime.date.today()

        for word in qs:
            if word[2] is None:
                words_with_scores.append((word[0], word[1], 0, today))
            elif word[3] < today:
                words_with_scores.append((word[0], word[1], word[2], today))
            else:
                words_with_scores.append(word)

        context['words_with_scores'] = words_with_scores
        return context


class QuizView(LoginRequiredMixin, View):
    """View responsible for rendering the server-side quiz functionality."""

    def post(self, *args, topic_id, **kwargs):
        """Receives the quiz results as a POST request, processes them, redirects user to the results page."""
        data = self.request.POST.get('results')
        results = json.loads(data)
        student = self.request.user

        results_page_data = process_results(results, student, topic_id)
        self.request.session['results'] = results_page_data

        # redirect to prevent results being resubmitted if page is refreshed
        return redirect(self.request.path)

    def get(self, *args, topic_id, **kwargs):
        """Renders the results page or a new quiz depending on whether a quiz has just been taken or not."""
        results = self.request.session.get('results', False)

        # a quiz has just been taken, render the results page
        if results:
            del self.request.session['results']
            return render(self.request, 'quizzes/quiz_results.html', results)

        # a new quiz is being started, obtain the question data and render the quiz page
        else:
            quiz_data = quiz_builder.get_quiz(self.request.user, topic_id=topic_id)
            if quiz_data['questions']:
                return render(self.request, 'quizzes/quiz.html', {'quiz': quiz_data})

            # handle the race condition if a Topic doesn't have enough words to create a new quiz
            else:
                return redirect(reverse('home'))

quizzes/templates/quizzes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bulma and custom CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'quizzes/css/base.css' %}">

    <title>{% block title %}Quizzes{% endblock %}</title>
</head>

<!-- Extend the body block to avoid inheriting the navbar -->
{% block body %}
    <body class="has-navbar-fixed-top">
    <!-- Navbar configuration -->
    <nav class="navbar is-fixed-top is-success has-text-weight-bold" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item {% if request.path == "/" %}is-active{% endif %}" href="{% url "home" %}">Home</a>
            {% if request.user.is_teacher %}
                <a class="navbar-item {% if request.path == "/data/dashboard/" %}is-active{% endif %}" href="{% url "dashboard" %}">Dashboard</a>
            {% else %}
                <a class="navbar-item {% if request.path == "/data/progress/" %}is-active{% endif %}" href="{% url "progress" %}">Progress</a>
            {% endif %}

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarElements">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarElements" class="navbar-menu">
            <!-- left-hand side -->
            <div class="navbar-start">
                <!-- items are in navbar brand so that they always display on small screens -->
            </div>
            <!-- right-hand side -->
            <div class="navbar-end">
                <a class="navbar-item {% if request.path == "/u/profile/" %}is-active{% endif %}" href="{% url 'profile' %}">{{ request.user }}</a>
                <div class="navbar-item">
                    <div class="buttons">
                        {% if user.is_authenticated %}
                            <a class="button is-light" href="{% url "logout" %}">Log out</a>
                        {% else %}
                            <a class="button is-dark" href="{% url "register" %}">Register</a>
                            <a class="button is-light" href="{% url "login" %}">Log in</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!-- Page content -->
    <section class="section">
        <div class="container">
            {% block content %}
                <!-- Page-specific body content goes here, while keeping the navbar -->
            {% endblock content %}
        </div>
    </section>
{% endblock body %}

<!-- Javascript Libraries-->


<!-- The following script is as per the Bulma docs: https://bulma.io/documentation/components/navbar/#navbar-menu -->
<script>
    document.addEventListener('DOMContentLoaded', () => {

        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Add a click event on each of them
        $navbarBurgers.forEach( el => {
            el.addEventListener('click', () => {

                // Get the target from the "data-target" attribute
                const target = el.dataset.target;
                const $target = document.getElementById(target);

                // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                el.classList.toggle('is-active');
                $target.classList.toggle('is-active');

            });
        });
    });
</script>
{% block scripts %}
    <!-- page specific scripts can be added here -->
{% endblock scripts %}
</body>
</html>

quizzes/templates/quizzes/home.html
{% extends "quizzes/base.html" %}
{% block title %}{{ block.super }}: Home{% endblock %}
{% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="notification is-{{message.tags}} is-light has-text-weight-semibold">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}

    <header class="title">Topics</header>

    <!-- Organise page into three columns -->
    <div class="columns is-multiline">

        {% if request.user.is_teacher %}
            <!-- 'Add New Topic/Word' card configuration -->
            <div class="column is-one-third">
                <div class="card ">
                    <header class="card-header">
                        <p class="card-header-title is-centered">Add Quiz Content</p>
                    </header>
                    <div class="card-content">
                        <div class="has-text-centered">
                            <div class="title is-1">➕</div>
                            <div class="buttons is-centered has-text-weight-bold">
                                <a class="button is-fullwidth is-info block" href="{% url 'topic_create' %}">+ New Topic</a>
                                <a class="button is-fullwidth is-info block" href="{% url 'topic_words' %}">View All Words</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        {% comment %} Generate a card for each Topic in the queryset {% endcomment %}
        {% for topic in topics %}
            <div class="column is-one-third">

                <!-- Topic card configuration -->
                <div class="card {% if not topic.is_visible or topic.word_count < 4 %}has-background-grey-lighter{% endif %}">
                    <header class="card-header">
                        <p class="card-header-title is-centered">{{ topic.name }}</p>
                    </header>
                    <div class="card-content">
                        <div class="has-text-centered">
                            <div class="title is-1">{{ topic.short_desc }}</div>
                            <div class="tags are-medium has-addons is-centered has-text-weight-semibold">
                                {% if request.user.is_teacher %}
                                    <span class="tag">Words In Topic:</span>
                                    <span class="tag {% if topic.word_count < 4 %}is-danger{% else %}is-success{% endif %}">{{ topic.word_count }}</span>
                                    <div class="content">
                                        <ul class="has-text-left is-size-7 ml-3 mt-0">
                                            {% if topic.is_hidden %}<li>Topic has been manually set to Hidden</li>{% endif %}
                                            {% if topic.word_count < 4 %}<li>Topic contains fewer than 4 Words</li>{% endif %}
                                            {% if topic.future_avail_from %}<li>Topic has been scheduled for {{ topic.available_from|date:"j F y" }}</li>{% endif %}
                                        </ul>
                                    </div>
                                {% else %}
                                    {% if topic.words_due > 0 %}
                                        <span class="tag">Words due:</span>
                                        <span class="tag is-danger">{{ topic.words_due }}</span>
                                    {% else %}
                                        <span class="tag is-success has-text-weight-semibold">Up to date!</span>
                                    {% endif %}
                                {% endif %}
                            </div>
                            <div class="buttons is-centered has-text-weight-bold">
                                {% if request.user.is_teacher %}
                                    <a class="button is-info is-fullwidth" href="{% url 'topic_update' topic.id %}">Edit Topic</a>
                                    <a class="button is-info is-fullwidth" href="{% url 'topic_words' topic.id %}">Add/Edit Words</a>
                                    <a class="button is-success is-fullwidth" href="{% url 'quiz' topic.id %}">Quiz Demo</a>
                                    <a class="button is-danger is-outlined is-fullwidth" href="{% url 'topic_delete' topic.id %}">Delete Topic...</a>
                                {% else %}
                                    <a class="button is-link is-fullwidth" href="{% url 'topic_detail' topic.id %}">Words</a>
                                    <a class="button is-success is-fullwidth" href="{% url 'quiz' topic.id %}">Quiz</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            {% if not request.user.is_teacher %}
                <p class="box has-background-warning">No Topics are currently available, come back later or ask your Teacher!</p>
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}

quizzes/templates/quizzes/quiz_results.html
{% extends "quizzes/base.html" %}

{% block title %}{{ block.super }}: Results{% endblock %}

{% block content %}
    {% load quiz_extras %}
    <div class="container is-widescreen">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-half">

                    <header class="has-text-centered block">
                        {% results_reaction correct total as reaction %}
                        <h1 class="title is-1 block">{{ reaction.1 }}</h1>
                        <h3 class="subtitle is-3 block">
                            {{ reaction.0 }} <br>You got {{ correct }}/{{ total }}.
                        </h3>
                    </header>

                    <div class="block">
                        <table class="table is-bordered is-striped is-hoverable is-fullwidth">
                            <thead>
                            <tr>
                                <th>Word</th>
                                <th>Target</th>
                                <th>Result</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for result in words %}
                                <tr>
                                    <td>{{ result.0 }}</td>
                                    <td>{{ result.1 }}</td>
                                    {% if result.2 %}
                                        <td class="has-background-success has-text-centered">✅</td>
                                    {% else %}
                                        <td class="has-background-danger-light has-text-centered">❌</td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="block">
                        <a class="button is-success is-pulled-right has-text-weight-semibold" href="{% url 'home' %}">Done</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

quizzes/templates/quizzes/topic_words.html
{% extends "quizzes/base.html" %}
{% load static %}
{% block title %}{{ block.super }}: {{ object.name }}{% endblock %}
{% block content %}
    <div class="columns is-centered">
        <div class="column is-three-fifths">

            {% comment %}TODO: replace this with Topic information{% endcomment %}
            <header class="block">
                <h1 class="title">{{ object.name }}</h1>
                <h3 class="subtitle">{{ object.long_desc }}</h3>
            </header>

            <div id="add-word-element" class="block">
                <button class="button is-warning block has-text-weight-semibold" id="add-word-button">+ Add Word</button>
            </div>

            <div id="add-word-ui" class="block" style="display: none">
                <div id="add-word-ui-form" class="is-marginless">
                </div>
            </div>

            <div class="block table-container">
                <table class="table is-bordered is-striped is-hoverable is-fullwidth" id="words-table">
                    <thead>
                    <tr>
                        <th>Origin</th>
                        <th>Target</th>
                        <th>Edit</th>
                        <th>Remove</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% include 'quizzes/word_list.html' %}
                    </tbody>
                </table>
            </div>

            <footer class="has-text-weight-semibold">
                <a class="button is-success is-pulled-right" href="{% url 'home' %}">Done</a>
            </footer>

        </div>
    </div>

{% endblock content %}
{% block scripts %}
    <script>let topicId = {{ topic_id }}</script>
    <script src="{% static 'quizzes/js/editor.js' %}"></script>
{% endblock %}

quizzes/templates/quizzes/word_form.html
{% load crispy_forms_tags %}
{% crispy form %}